#!/bin/sh

#ALIASES

#more neovim support
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" 

#youtube-dl
alias yta="noglob youtube-dl --extract-audio --audio-format mp3 -o '%(title)s.%(ext)s'" #noglob for zsh links, -o for nice file names, a for audio, v for video
alias ytv="noglob youtube-dl"

#git 
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME' #bare git repo
alias gls="git status" #git ls
alias gcm="git commit -m"
alias gpos="git push origin master"
alias gad="git add"
alias gadall="git add -A" #git add all
alias gadupd="git add -u" #git add updated files
alias glog="git log --oneline" #will change to something better soon
alias smic="sudo make install clean" #very useful for compiling suckless utilities

#common commands
alias ls="ls -h --group-directories-first" #cool ls
alias grep="grep --color=auto" #pretty grep
alias lsg="ls | grep -i" #case insensitive search from output
alias lsa="ls -a" #list all
alias cp="cp -v" #verbose cp
alias rm="rm -vI" #I've lost many things before
alias z="zathura" #thank the heavens

#going to places faster
alias mus="cs ~/Desktop/personal/music" #cs is defined later
alias vid="cs ~/Desktop/personal/videos" #but it's basically just cd -> ls
alias ut="cs ~/Desktop/academic/ut_austin"
alias tb="cs ~/Desktop/academic/textbooks"
alias help="vim ~/Desktop/personal/information/linux_setup/common_terminal_commands.txt"
alias todo="vim ~/Desktop/personal/information/linux_setup/todo_list.txt"
alias math="vim ~/Desktop/personal/useful_information/math_resources.txt"
alias bk="vim ~/Desktop/personal/useful_information/useful_links.txt"
alias blog="vim ~/Desktop/personal/useful_information/blog_posts.txt"
alias mirai="vim ~/Desktop/personal/useful_information/future_todolist.txt"
alias library="vim ~/Desktop/personal/books/books_read.txt"

#backing up 
alias fullbackup="sudo rsync -rvz --delete ~/ /run/media/simon/info" #makes local backup of home directory: -r for recursive, -v for verbose, -z for compression, --delete to delete files on backup not on local (mirror image)

#setting pretty themes
alias newtheme="wal -i ~/Desktop/personal/anime/wallpaper_selections" #randomizes bg and sets new theme with pywal
alias newthemelight="wal -li ~/Desktop/personal/anime/light_wallpapers" #newtheme, but light mode

#FUNCTIONS

#nord theme
nord() { 
	wal --theme "base16-nord" &&
	xwallpaper --zoom "/home/simon/Desktop/personal/anime/wallpaper_selections/nord_ocean_jellyfish.png";
} 

#moving around
cs() { cd "$1" && ls; } #cd then ls
csa() { cd "$1" && ls -a; } #cd then ls -a

#git management
cpos() {config push origin master && config push home master;} #push all dotfiles

#nnn cd to directory on quit
n () 
{
	if [ -n $NNNLVL ] && [ "${NNNLVL:-0}" -ge 1 ]; then
		echo "nnn is already running"
		return 
	fi

	export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
	nnn "$@"

	if [ -f "$NNN_TMPFILE" ]; then
		. "$NNN_TMPFILE"
		rm -f "$NNN_TMPFILE" > /dev/null
	fi
}

